### DISCUSSION TITLE
How do you reccomend we work with large levels?

### DISCUSSION THREAD

**Discussion by honne23** [Trouv/bevy_ecs_ldtk#185] [Q&A] [answered]
I'm trying to create a large level in ldtk (1600 x 900) and load them into my game however it seems to crash due to too many textures trying to load onto the GPU at once. I noticed that `bevy_ecs_tilemap` under the hood implements `Frustum culling` by default, but as I understand this doesn't apply to layered tiles.

```
thread 'Compute Task Pool (3)' panicked at 'wgpu error: Validation Error

Caused by:
    In Device::create_texture
      note: label = `texture_array`
    Dimension Z value 3128 exceeds the limit of 2048
```

I tried to load the `LdtkWorldBundle` with `visibility: Visibility::Hidden, computed_visibility::HIDDEN` but this had no effect. I'm assuming that the solution probably involves ray-casting from the camera onto the tiles and only rendering those in view?

**Comment by Trouv** [comment]
Hi - This is because of a sort-of bug that was fixed recently: https://github.com/Trouv/bevy_ecs_ldtk/pull/183. You can use this fix now by patching in that branch in your `Cargo.toml`
```toml
[patch.crates-io]
bevy_ecs_ldtk = { git = "https://github.com/Trouv/bevy_ecs_ldtk", branch = "fix/smaller-cached-white-image" }
```

I will likely release a new version in the next week or so w/ this fix implemented.

Edit: There actually is another possibility that this is a problem w/ your tileset being too large for your current wgpu settings, or static hardware limitations. If you're still experiencing this issue after patching, try this too: https://github.com/Trouv/bevy_ecs_ldtk/issues/176#issuecomment-1500410802

**Reply by Trouv** [reply]
Now you will need to depend on the `main` branch - since that branch has been merged (and deleted).
```toml
[patch.crates-io]
bevy_ecs_ldtk = { git = "https://github.com/Trouv/bevy_ecs_ldtk", branch = "main" }
```
