### DISCUSSION TITLE
What's the best way to clean/despawn everything?

### DISCUSSION THREAD

**Discussion by stephenjjbrown** [Trouv/bevy_ecs_ldtk#218] [Q&A] [answered]
If the player wants to return to the main menu, for instance. Right now I can query for LevelSet and call despawn_recursive, but once the player starts a new game and a new LdtkWorldBundle is spawned, textures start to break and I get other strange behavior. So I think I must not be getting everything?

**Comment by Trouv** [comment, marked as answer]
> textures start to break and I get other strange behavior.

This sounds like a bug that's in `bevy_ecs_tilemap` 0.11. You may have better luck here with this patch:
```toml
[patch.crates-io]
bevy_ecs_tilemap = { git = "http://github.com/StarArawn/bevy_ecs_tilemap", version = "0.11", branch = "main" }
```

As for the best way to despawn everything, it depends on whether or not you want to keep the `LdtkWorldBundle` you've already spawned around. If you don't then what you're doing is probably fine. If you want to keep it around (in case you're not storing the `Handle<LdtkAsset>` anywhere else), it may suffice to empty the `LevelSet` collection instead, but it might get automatically re-populated if you have a `LevelSelection` resource inserted.
