### DISCUSSION TITLE
Bevy Jam 4 usage

### DISCUSSION THREAD

**Discussion by Trouv** [Trouv/bevy_ecs_ldtk#273] [Announcements]
Hello jammers! Currently, `bevy_ecs_tilemap` and this plugin have not had a release compatible with Bevy `0.12`. However, both of these plugins do have branches that upgrade to this version. Rust allows you to use git dependencies, so you're not completely out of luck for using LDtk in this jam.

Update your `Cargo.toml` to depend on this plugin's `feat/bevy-0.12` branch, and patch in `bevy_ecs_tilemap`'s 0.12 upgrade PR. It's important that you treat the latter as a patch, not a normal dependency.

```toml
[dependencies]
bevy = "0.12"
bevy_ecs_ldtk = { version = "0.8", git = "https://github.com/trouv/bevy_ecs_ldtk", branch = "feat/bevy-0.12" }

[patch.crates-io]
bevy_ecs_tilemap = { git = "https://github.com/divark/bevy_ecs_tilemap", branch = "0.12-fixes" }
```

If you're new to LDtk or to this plugin, you may be interested in this "tile based game" tutorial: https://trouv.github.io/bevy_ecs_ldtk/latest/tutorials/tile-based-game/index.html

Furthermore, do not hesitate to ask for help in this repository or in the Bevy discord (specifically the bevy_ecs_ldtk thread in the crate-help channel).
