### ISSUE TITLE
Bevy 0.12 support

### ISSUE THREAD

**Issue by Rigidity** [Trouv/bevy_ecs_ldtk#259]
Hey, [Bevy 0.12](https://bevyengine.org/news/bevy-0-12/) was recently released, I'm wondering if there's any current plans for this crate to support it?

**Comment by Trouv** [comment]
Yes, we will support it. It tends to take a little longer for this plugin to upgrade since it depends on `bevy_ecs_tilemap` upgrading. That plugin tends to be a little slow to upgrade on its own too since it does so much custom rendering stuff.

So this depends on https://github.com/StarArawn/bevy_ecs_tilemap/issues/488

**Comment by focustense** [comment]
Will there be a change log, migration guide, anything of that sort? I presume that the update for bevy 0.12 will also include the rearchitecting of all the various level components.

Replacing all the code dependent on `Handle<&LdtkLevel>` with the new loaded-level system is going to be the biggest one for me, at least. But in general there seems to be more breaking changes than I recall from previous updates.

It looks like the `bevy_ecs_ldtk` update is scheduled to drop very soon; 4 days ago it was announced "in a few days".

**Comment by Trouv** [comment]
I've already written a migration guide in the new WIP `bevy_ecs_ldtk` book: https://trouv.github.io/bevy_ecs_ldtk/latest/how-to-guides/migration-guides/migrate-from-0.8-to-0.9.html

Hope this helps!

**Comment by Microwonk** [comment]
I am looking for version 0.9.0, has it been released yet or is it in progress to migrate to bevy 0.12.0?

**Comment by Trouv** [comment]
> I am looking for version 0.9.0, has it been released yet or is it in progress to migrate to bevy 0.12.0?

We're currently waiting for `bevy_ecs_tilemap` version `0.12` to release. However, both plugins have unreleased upgrades to the new version in their repositories. You can add this to your `Cargo.toml` to try it out:
```toml
[patch.crates-io]
bevy_ecs_ldtk = { git = "https://github.com/trouv/bevy_ecs_ldtk", branch = "feat/bevy-0.12" }
bevy_ecs_tilemap = { git = "https://github.com/StarArawn/bevy_ecs_tilemap", branch = "main" }
```
