### ISSUE TITLE
Usage help for Bevy 0.13 users

### ISSUE THREAD

**Issue by icorbrey** [Trouv/bevy_ecs_ldtk#321]
You will likely be running into a host of problems attempting to use this plugin with Bevy 0.13 as `bevy_ecs_tilemap` has not yet released changes to support 0.13 (see StarArawn/bevy_ecs_tilemap#516). To resolve this, add the following to your `Cargo.toml`:

```toml
[dependencies]
# Use unstable version for Bevy 0.13 support
bevy_ecs_ldtk = { git = "https://github.com/Trouv/bevy_ecs_ldtk.git" } 

[patch.crates-io]
# Patch unstable version to resolve conflicting dependencies from bevy_ecs_ldtk
bevy_ecs_tilemap = { git = "https://github.com/StarArawn/bevy_ecs_tilemap" }
```

@Trouv feel free to close this if you deem so, but I thought it would be helpful for new users trying to figure this out.
