### ISSUE TITLE
Bevy asset throws an error

### ISSUE THREAD

**Issue by MadMed677** [Trouv/bevy_ecs_ldtk#79]
# Problem

I tried to set up just a basic example but faced the problem

```
2022-04-20T17:03:51.657636Z  WARN bevy_asset::asset_server: encountered an error while loading an asset:
unknown variant `PrependIndexToLevelFileNames`,
expected `DiscardPreCsvIntGrid` or `IgnoreBackupSuggest` at line 35 column 41
```

I used an example in `basic.rs` but I got the same problem in others too.

# Environment
__Cargo.toml__ file
```
[dependencies]
bevy = {version = "0.6", default-features = false}
bevy_ecs_ldtk = "0.2"
```

__main.rs__ file the same as `examples/basic.rs`

As I see the problem with the `flag` property in the `.ldtk` file.
Bevy assets don't work to play with it `"flags": ["PrependIndexToLevelFileNames"]`

**Comment by Trouv** [comment]
My guess is you're using a newer version of LDtk. `bevy_ecs_ldtk` 0.2 doesn't support LDtk 1.0+. However, support for LDtk 1.1 is available on the main branch if you want to point your bevy_ecs_ldtk dependency there:
```toml
[dependencies]
bevy = {version = "0.6", default-features = false}
bevy_ecs_ldtk = { git = "https://github.com/Trouv/bevy_ecs_ldtk", rev = "7e499ab89b9049146255fa4b7543763dcc7adbf9" }
```
0.3 will have support for the newer LDtk but I'm waiting for `bevy_ecs_tilemap` 0.6 before cutting a new release.
