### ISSUE TITLE
Tilemap shows wrong tiles when using spacing and atlas

### ISSUE THREAD

**Issue by svenallers** [Trouv/bevy_ecs_ldtk#94]
Hi,
I currently have the issue that the rendered tilemap does not look at all like the one I created.

Here is how it looks in LDtk:
<img width="1792" alt="ldtk" src="https://user-images.githubusercontent.com/7449886/173254281-12a0cbf7-d793-4916-922b-7af67941ae31.png">
 
And here is how it is rendered when starting my game:
<img width="1283" alt="bevy" src="https://user-images.githubusercontent.com/7449886/173254311-306bf52d-6abf-4626-8140-c4e43a41a996.png">

The tileset is using a spacing of 2px and therefore I enabled the atlas feature. My code currently looks like this:

_main.rs_
```rust
use bevy::prelude::*;
use bevy_ecs_ldtk::prelude::*;

fn main() {
    App::new()
        .add_plugins(DefaultPlugins)
        .add_plugin(LdtkPlugin)
        .add_startup_system(setup)
        .insert_resource(LevelSelection::Index(0))
        .run();
}

fn setup(mut commands: Commands, asset_server: Res<AssetServer>) {
    commands.spawn_bundle(OrthographicCameraBundle::new_2d());

    commands.spawn_bundle(LdtkWorldBundle {
        ldtk_handle: asset_server.load("racing-track.ldtk"),
        ..Default::default()
    });
}
```

_cargo.toml_
```toml
[package]
edition = "2021"
name = "bevy-racer"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.7"
bevy_ecs_ldtk = {version = "0.3", features = ["atlas"]}
```

A link to the full codebase, having the issue including the ldtk file and resources:  https://github.com/svenallers/bevy-racer/commit/1e7e76d63d7247ea3a73b31679bfa75717afdd16

Could also be that the issue is on me, but I have no clue how to solve it.
